//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakipWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresleme
    {
        public int Id { get; set; }
        public string StokKodu { get; set; }
        public string BosaltmaYontemi { get; set; }
        public Nullable<bool> GeciciKabul { get; set; }
        public string Hasar { get; set; }
        public Nullable<bool> MalKabul { get; set; }
        public string Yerleştirme { get; set; }
        public string YüklemeBosaltmaAlani { get; set; }
    }
}
