//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakipWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StokDBEntities1 : DbContext
    {
        public StokDBEntities1()
            : base("name=StokDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adresleme> Adresleme { get; set; }
        public virtual DbSet<StokKart> StokKart { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
